import { useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { LockKeyhole, Mail } from 'lucide-react';
import Layout from '../components/Layout.jsx';
import { useAuth } from '../context/AuthContext.jsx';
import { messageFromError } from '../lib/api.js';

export default function Login() { const { login } = useAuth(); const navigate=useNavigate(); const location=useLocation(); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
 const submit=async(e)=>{e.preventDefault();setError('');setLoading(true);try{const user=await login(email,password);navigate(location.state?.from || (user.role==='admin'?'/admin':'/student'),{replace:true});}catch(e){setError(messageFromError(e));}finally{setLoading(false)}};
 return <Layout><div className="grid min-h-[calc(100vh-80px)] place-items-center px-5 py-12"><motion.form initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} onSubmit={submit} className="glass w-full max-w-md rounded-3xl p-8"><div className="mb-8"><p className="text-sm font-bold uppercase tracking-[.25em] text-cyan-300">Private access</p><h1 className="mt-2 text-3xl font-black text-white">Welcome back</h1><p className="mt-2 text-sm text-slate-400">Students receive their accounts from the teacher.</p></div>{error&&<div className="mb-4 rounded-xl border border-rose-300/20 bg-rose-400/10 p-3 text-sm text-rose-200">{error}</div>}<label className="block text-sm text-slate-300">Email<div className="mt-2 flex items-center gap-2 rounded-xl border border-white/10 bg-slate-950/50 px-3"><Mail size={17} className="text-slate-500"/><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="w-full bg-transparent px-2 py-3 outline-none" placeholder="student@example.com"/></div></label><label className="mt-5 block text-sm text-slate-300">Password<div className="mt-2 flex items-center gap-2 rounded-xl border border-white/10 bg-slate-950/50 px-3"><LockKeyhole size={17} className="text-slate-500"/><input required type="password" value={password} onChange={e=>setPassword(e.target.value)} className="w-full bg-transparent px-2 py-3 outline-none" placeholder="••••••••"/></div></label><button disabled={loading} className="mt-7 w-full rounded-xl bg-cyan-400 px-5 py-3 font-bold text-slate-950 disabled:opacity-50">{loading?'Signing in...':'Login'}</button></motion.form></div></Layout>; }
