import { useEffect, useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { CheckCircle2, Clock3, PlayCircle } from 'lucide-react';
import Layout from '../components/Layout.jsx';
import LectureCard from '../components/LectureCard.jsx';
import StatCard from '../components/StatCard.jsx';
import { api, messageFromError } from '../lib/api.js';
import { useAuth } from '../context/AuthContext.jsx';

export default function StudentDashboard(){const{user}=useAuth();const[lectures,setLectures]=useState([]);const[error,setError]=useState('');useEffect(()=>{api.get('/lectures/student').then(r=>setLectures(r.data.data.lectures)).catch(e=>setError(messageFromError(e)))},[]);const done=lectures.filter(x=>x.completed).length;const next=lectures.find(x=>x.canOpen&&!x.completed);const pct=useMemo(()=>lectures.length?Math.round(done/lectures.length*100):0,[done,lectures.length]);return <Layout><div className="mx-auto max-w-7xl px-5 py-10"><motion.div initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} className="glass rounded-3xl p-7 md:p-10"><p className="text-cyan-300">Welcome back, {user?.name?.split(' ')[0]} 👋</p><h1 className="mt-2 text-4xl font-black text-white">Keep learning.</h1><div className="mt-8 grid gap-4 md:grid-cols-3"><StatCard icon={<CheckCircle2/>} label="Completed lectures" value={`${done}/${lectures.length}`}/><StatCard icon={<Clock3/>} label="Progress" value={`${pct}%`}/><StatCard icon={<PlayCircle/>} label="Next lesson" value={next?`#${next.order}`:'All done'}/></div><div className="mt-8"><div className="mb-2 flex justify-between text-sm"><span className="text-slate-400">Course progress</span><span className="font-bold text-cyan-300">{pct}%</span></div><div className="h-3 overflow-hidden rounded-full bg-white/10"><motion.div initial={{width:0}} animate={{width:`${pct}%`}} className="h-full rounded-full bg-cyan-400"/></div></div></motion.div><div className="mt-12"><h2 className="mb-6 text-2xl font-bold text-white">Your lectures</h2>{error?<p className="text-rose-300">{error}</p>:lectures.length?<div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{lectures.map(l=><LectureCard key={l.id} lecture={l} student/>)}</div>:<div className="glass rounded-2xl p-8 text-slate-400">Your teacher has not published any lectures yet.</div>}</div></div></Layout>}
